import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { FirstHeader, MiddleHeader, LastHeader } from "@/app/components/header";
import Footer from "@/app/components/footer";
import FloatingButton from "@/components/ui/FloatingButton";
import { CartProvider } from "@/hooks/CartContext";
import { ClerkProvider, SignInButton, SignedOut, SignedIn } from "@clerk/nextjs"; 
import AdminUserButton from "@/app/components/AdminUserButton"; // Import the client component

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <head>
        {/* ✅ Add Favicon to Fix Console Error */}
        <link rel="icon" href="/favicon.ico" sizes="any" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ClerkProvider>
          <CartProvider>
            <div>
              <FirstHeader />
              <MiddleHeader />
              <LastHeader />
            </div>

            {/* Conditionally render SignInButton only when the user is signed out */}
            <SignedOut>
              <SignInButton>
                <button className="text-white border-none cursor-default "></button>
              </SignInButton>
            </SignedOut>

            {/* Use AdminUserButton client-side component */}
            <SignedIn>
              <AdminUserButton />
            </SignedIn>

            <main>{children}</main>

            <Footer />

            <div className="md:hidden fixed bottom-4 right-4 z-50">
              <FloatingButton />
            </div>
          </CartProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
